// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/Stanislav-Shchelokovskiy/clean-code/service/ds"
	mock "github.com/stretchr/testify/mock"
)

// NewMockByIDSearcher creates a new instance of MockByIDSearcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockByIDSearcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockByIDSearcher {
	mock := &MockByIDSearcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockByIDSearcher is an autogenerated mock type for the ByIDSearcher type
type MockByIDSearcher struct {
	mock.Mock
}

type MockByIDSearcher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockByIDSearcher) EXPECT() *MockByIDSearcher_Expecter {
	return &MockByIDSearcher_Expecter{mock: &_m.Mock}
}

// SearchByIDs provides a mock function for the type MockByIDSearcher
func (_mock *MockByIDSearcher) SearchByIDs(ids []int64) ([]*ds.Item, error) {
	ret := _mock.Called(ids)

	if len(ret) == 0 {
		panic("no return value specified for SearchByIDs")
	}

	var r0 []*ds.Item
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]int64) ([]*ds.Item, error)); ok {
		return returnFunc(ids)
	}
	if returnFunc, ok := ret.Get(0).(func([]int64) []*ds.Item); ok {
		r0 = returnFunc(ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*ds.Item)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]int64) error); ok {
		r1 = returnFunc(ids)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockByIDSearcher_SearchByIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchByIDs'
type MockByIDSearcher_SearchByIDs_Call struct {
	*mock.Call
}

// SearchByIDs is a helper method to define mock.On call
//   - ids []int64
func (_e *MockByIDSearcher_Expecter) SearchByIDs(ids interface{}) *MockByIDSearcher_SearchByIDs_Call {
	return &MockByIDSearcher_SearchByIDs_Call{Call: _e.mock.On("SearchByIDs", ids)}
}

func (_c *MockByIDSearcher_SearchByIDs_Call) Run(run func(ids []int64)) *MockByIDSearcher_SearchByIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []int64
		if args[0] != nil {
			arg0 = args[0].([]int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockByIDSearcher_SearchByIDs_Call) Return(items []*ds.Item, err error) *MockByIDSearcher_SearchByIDs_Call {
	_c.Call.Return(items, err)
	return _c
}

func (_c *MockByIDSearcher_SearchByIDs_Call) RunAndReturn(run func(ids []int64) ([]*ds.Item, error)) *MockByIDSearcher_SearchByIDs_Call {
	_c.Call.Return(run)
	return _c
}
