// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/Stanislav-Shchelokovskiy/clean-code/service/ds"
	mock "github.com/stretchr/testify/mock"
)

// NewMockByNameSearcher creates a new instance of MockByNameSearcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockByNameSearcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockByNameSearcher {
	mock := &MockByNameSearcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockByNameSearcher is an autogenerated mock type for the ByNameSearcher type
type MockByNameSearcher struct {
	mock.Mock
}

type MockByNameSearcher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockByNameSearcher) EXPECT() *MockByNameSearcher_Expecter {
	return &MockByNameSearcher_Expecter{mock: &_m.Mock}
}

// SearchByName provides a mock function for the type MockByNameSearcher
func (_mock *MockByNameSearcher) SearchByName(name string) ([]*ds.Item, error) {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for SearchByName")
	}

	var r0 []*ds.Item
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]*ds.Item, error)); ok {
		return returnFunc(name)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []*ds.Item); ok {
		r0 = returnFunc(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*ds.Item)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockByNameSearcher_SearchByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchByName'
type MockByNameSearcher_SearchByName_Call struct {
	*mock.Call
}

// SearchByName is a helper method to define mock.On call
//   - name string
func (_e *MockByNameSearcher_Expecter) SearchByName(name interface{}) *MockByNameSearcher_SearchByName_Call {
	return &MockByNameSearcher_SearchByName_Call{Call: _e.mock.On("SearchByName", name)}
}

func (_c *MockByNameSearcher_SearchByName_Call) Run(run func(name string)) *MockByNameSearcher_SearchByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockByNameSearcher_SearchByName_Call) Return(items []*ds.Item, err error) *MockByNameSearcher_SearchByName_Call {
	_c.Call.Return(items, err)
	return _c
}

func (_c *MockByNameSearcher_SearchByName_Call) RunAndReturn(run func(name string) ([]*ds.Item, error)) *MockByNameSearcher_SearchByName_Call {
	_c.Call.Return(run)
	return _c
}
