// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepo creates a new instance of MockRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepo {
	mock := &MockRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepo is an autogenerated mock type for the Repo type
type MockRepo struct {
	mock.Mock
}

type MockRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepo) EXPECT() *MockRepo_Expecter {
	return &MockRepo_Expecter{mock: &_m.Mock}
}

// GetItemIDs provides a mock function for the type MockRepo
func (_mock *MockRepo) GetItemIDs(ids []int64) ([]int64, error) {
	ret := _mock.Called(ids)

	if len(ret) == 0 {
		panic("no return value specified for GetItemIDs")
	}

	var r0 []int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]int64) ([]int64, error)); ok {
		return returnFunc(ids)
	}
	if returnFunc, ok := ret.Get(0).(func([]int64) []int64); ok {
		r0 = returnFunc(ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]int64)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]int64) error); ok {
		r1 = returnFunc(ids)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepo_GetItemIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetItemIDs'
type MockRepo_GetItemIDs_Call struct {
	*mock.Call
}

// GetItemIDs is a helper method to define mock.On call
//   - ids []int64
func (_e *MockRepo_Expecter) GetItemIDs(ids interface{}) *MockRepo_GetItemIDs_Call {
	return &MockRepo_GetItemIDs_Call{Call: _e.mock.On("GetItemIDs", ids)}
}

func (_c *MockRepo_GetItemIDs_Call) Run(run func(ids []int64)) *MockRepo_GetItemIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []int64
		if args[0] != nil {
			arg0 = args[0].([]int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepo_GetItemIDs_Call) Return(int64s []int64, err error) *MockRepo_GetItemIDs_Call {
	_c.Call.Return(int64s, err)
	return _c
}

func (_c *MockRepo_GetItemIDs_Call) RunAndReturn(run func(ids []int64) ([]int64, error)) *MockRepo_GetItemIDs_Call {
	_c.Call.Return(run)
	return _c
}
