// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockSearcher creates a new instance of MockSearcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSearcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSearcher {
	mock := &MockSearcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSearcher is an autogenerated mock type for the Searcher type
type MockSearcher struct {
	mock.Mock
}

type MockSearcher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSearcher) EXPECT() *MockSearcher_Expecter {
	return &MockSearcher_Expecter{mock: &_m.Mock}
}

// SearchByName provides a mock function for the type MockSearcher
func (_mock *MockSearcher) SearchByName(name string) ([]int64, map[int64]string, error) {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for SearchByName")
	}

	var r0 []int64
	var r1 map[int64]string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]int64, map[int64]string, error)); ok {
		return returnFunc(name)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []int64); ok {
		r0 = returnFunc(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]int64)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) map[int64]string); ok {
		r1 = returnFunc(name)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(map[int64]string)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(string) error); ok {
		r2 = returnFunc(name)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockSearcher_SearchByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchByName'
type MockSearcher_SearchByName_Call struct {
	*mock.Call
}

// SearchByName is a helper method to define mock.On call
//   - name string
func (_e *MockSearcher_Expecter) SearchByName(name interface{}) *MockSearcher_SearchByName_Call {
	return &MockSearcher_SearchByName_Call{Call: _e.mock.On("SearchByName", name)}
}

func (_c *MockSearcher_SearchByName_Call) Run(run func(name string)) *MockSearcher_SearchByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSearcher_SearchByName_Call) Return(int64s []int64, int64ToString map[int64]string, err error) *MockSearcher_SearchByName_Call {
	_c.Call.Return(int64s, int64ToString, err)
	return _c
}

func (_c *MockSearcher_SearchByName_Call) RunAndReturn(run func(name string) ([]int64, map[int64]string, error)) *MockSearcher_SearchByName_Call {
	_c.Call.Return(run)
	return _c
}
