// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/Stanislav-Shchelokovskiy/clean-code/service/ds"
	mock "github.com/stretchr/testify/mock"
)

// NewMockInternalService creates a new instance of MockInternalService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInternalService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInternalService {
	mock := &MockInternalService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockInternalService is an autogenerated mock type for the internalService type
type MockInternalService struct {
	mock.Mock
}

type MockInternalService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInternalService) EXPECT() *MockInternalService_Expecter {
	return &MockInternalService_Expecter{mock: &_m.Mock}
}

// SearchByIDs provides a mock function for the type MockInternalService
func (_mock *MockInternalService) SearchByIDs(ids []int64) ([]*ds.Item, error) {
	ret := _mock.Called(ids)

	if len(ret) == 0 {
		panic("no return value specified for SearchByIDs")
	}

	var r0 []*ds.Item
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]int64) ([]*ds.Item, error)); ok {
		return returnFunc(ids)
	}
	if returnFunc, ok := ret.Get(0).(func([]int64) []*ds.Item); ok {
		r0 = returnFunc(ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*ds.Item)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]int64) error); ok {
		r1 = returnFunc(ids)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockInternalService_SearchByIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchByIDs'
type MockInternalService_SearchByIDs_Call struct {
	*mock.Call
}

// SearchByIDs is a helper method to define mock.On call
//   - ids []int64
func (_e *MockInternalService_Expecter) SearchByIDs(ids interface{}) *MockInternalService_SearchByIDs_Call {
	return &MockInternalService_SearchByIDs_Call{Call: _e.mock.On("SearchByIDs", ids)}
}

func (_c *MockInternalService_SearchByIDs_Call) Run(run func(ids []int64)) *MockInternalService_SearchByIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []int64
		if args[0] != nil {
			arg0 = args[0].([]int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockInternalService_SearchByIDs_Call) Return(items []*ds.Item, err error) *MockInternalService_SearchByIDs_Call {
	_c.Call.Return(items, err)
	return _c
}

func (_c *MockInternalService_SearchByIDs_Call) RunAndReturn(run func(ids []int64) ([]*ds.Item, error)) *MockInternalService_SearchByIDs_Call {
	_c.Call.Return(run)
	return _c
}

// SearchByName provides a mock function for the type MockInternalService
func (_mock *MockInternalService) SearchByName(name string) ([]*ds.Item, error) {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for SearchByName")
	}

	var r0 []*ds.Item
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]*ds.Item, error)); ok {
		return returnFunc(name)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []*ds.Item); ok {
		r0 = returnFunc(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*ds.Item)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockInternalService_SearchByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchByName'
type MockInternalService_SearchByName_Call struct {
	*mock.Call
}

// SearchByName is a helper method to define mock.On call
//   - name string
func (_e *MockInternalService_Expecter) SearchByName(name interface{}) *MockInternalService_SearchByName_Call {
	return &MockInternalService_SearchByName_Call{Call: _e.mock.On("SearchByName", name)}
}

func (_c *MockInternalService_SearchByName_Call) Run(run func(name string)) *MockInternalService_SearchByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockInternalService_SearchByName_Call) Return(items []*ds.Item, err error) *MockInternalService_SearchByName_Call {
	_c.Call.Return(items, err)
	return _c
}

func (_c *MockInternalService_SearchByName_Call) RunAndReturn(run func(name string) ([]*ds.Item, error)) *MockInternalService_SearchByName_Call {
	_c.Call.Return(run)
	return _c
}
