// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockItemNamesGetter creates a new instance of MockItemNamesGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockItemNamesGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockItemNamesGetter {
	mock := &MockItemNamesGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockItemNamesGetter is an autogenerated mock type for the ItemNamesGetter type
type MockItemNamesGetter struct {
	mock.Mock
}

type MockItemNamesGetter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockItemNamesGetter) EXPECT() *MockItemNamesGetter_Expecter {
	return &MockItemNamesGetter_Expecter{mock: &_m.Mock}
}

// GetNames provides a mock function for the type MockItemNamesGetter
func (_mock *MockItemNamesGetter) GetNames(ids []int64) (map[int64]string, error) {
	ret := _mock.Called(ids)

	if len(ret) == 0 {
		panic("no return value specified for GetNames")
	}

	var r0 map[int64]string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]int64) (map[int64]string, error)); ok {
		return returnFunc(ids)
	}
	if returnFunc, ok := ret.Get(0).(func([]int64) map[int64]string); ok {
		r0 = returnFunc(ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[int64]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]int64) error); ok {
		r1 = returnFunc(ids)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockItemNamesGetter_GetNames_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNames'
type MockItemNamesGetter_GetNames_Call struct {
	*mock.Call
}

// GetNames is a helper method to define mock.On call
//   - ids []int64
func (_e *MockItemNamesGetter_Expecter) GetNames(ids interface{}) *MockItemNamesGetter_GetNames_Call {
	return &MockItemNamesGetter_GetNames_Call{Call: _e.mock.On("GetNames", ids)}
}

func (_c *MockItemNamesGetter_GetNames_Call) Run(run func(ids []int64)) *MockItemNamesGetter_GetNames_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []int64
		if args[0] != nil {
			arg0 = args[0].([]int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockItemNamesGetter_GetNames_Call) Return(int64ToString map[int64]string, err error) *MockItemNamesGetter_GetNames_Call {
	_c.Call.Return(int64ToString, err)
	return _c
}

func (_c *MockItemNamesGetter_GetNames_Call) RunAndReturn(run func(ids []int64) (map[int64]string, error)) *MockItemNamesGetter_GetNames_Call {
	_c.Call.Return(run)
	return _c
}
