// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/Stanislav-Shchelokovskiy/clean-code/service/ds"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRawItemsSearcher creates a new instance of MockRawItemsSearcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRawItemsSearcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRawItemsSearcher {
	mock := &MockRawItemsSearcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRawItemsSearcher is an autogenerated mock type for the RawItemsSearcher type
type MockRawItemsSearcher struct {
	mock.Mock
}

type MockRawItemsSearcher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRawItemsSearcher) EXPECT() *MockRawItemsSearcher_Expecter {
	return &MockRawItemsSearcher_Expecter{mock: &_m.Mock}
}

// SearchByName provides a mock function for the type MockRawItemsSearcher
func (_mock *MockRawItemsSearcher) SearchByName(name string) ([]*ds.RawItem, error) {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for SearchByName")
	}

	var r0 []*ds.RawItem
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]*ds.RawItem, error)); ok {
		return returnFunc(name)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []*ds.RawItem); ok {
		r0 = returnFunc(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*ds.RawItem)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRawItemsSearcher_SearchByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchByName'
type MockRawItemsSearcher_SearchByName_Call struct {
	*mock.Call
}

// SearchByName is a helper method to define mock.On call
//   - name string
func (_e *MockRawItemsSearcher_Expecter) SearchByName(name interface{}) *MockRawItemsSearcher_SearchByName_Call {
	return &MockRawItemsSearcher_SearchByName_Call{Call: _e.mock.On("SearchByName", name)}
}

func (_c *MockRawItemsSearcher_SearchByName_Call) Run(run func(name string)) *MockRawItemsSearcher_SearchByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRawItemsSearcher_SearchByName_Call) Return(rawItems []*ds.RawItem, err error) *MockRawItemsSearcher_SearchByName_Call {
	_c.Call.Return(rawItems, err)
	return _c
}

func (_c *MockRawItemsSearcher_SearchByName_Call) RunAndReturn(run func(name string) ([]*ds.RawItem, error)) *MockRawItemsSearcher_SearchByName_Call {
	_c.Call.Return(run)
	return _c
}
